"""empty message

Revision ID: 954638258de8
Revises: 179a2b6899c5
Create Date: 2023-05-01 14:56:42.104982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954638258de8'
down_revision = '179a2b6899c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_game_id_video_games'), 'video_games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_game_id_video_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
